language: node_js
node_js:
  - "12"
dist: trusty
sudo: required
services:
  - docker
env:
  - IMAGE_NAME='infrastructr/deck-ui'
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - ng test --watch=false --codeCoverage=true
  - ng build --prod
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker build . -t "$IMAGE_NAME:$TRAVIS_BRANCH" -t "$IMAGE_NAME:latest"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$IMAGE_NAME:$TRAVIS_BRANCH" && docker push "$IMAGE_NAME:latest"
