language: node_js
node_js:
  - "12"
dist: trusty
sudo: required
services:
  - docker
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - ng test --watch=false
  - ng build --prod
after_success:
  - docker build . -t "$IMAGE_NAME:$TRAVIS_BRANCH" -t "$IMAGE_NAME:latest"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$IMAGE_NAME:$TRAVIS_BRANCH" && docker push "$IMAGE_NAME:latest"
